apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: efk
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /fluentd/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      format json
    </source>

    <filter kubernetes.**>
      @type parser
      key_name log
      reserve_data false
      remove_key_name_field true
      emit_invalid_record_to_error false
      <parse>
        @type json
        time_key @timestamp
        time_type string
        time_format %Y-%m-%dT%H:%M:%S.%L%z
      </parse>
    </filter>

    <match **>
      @type elasticsearch
      host elasticsearch.efk.svc.cluster.local
      port 9200
      logstash_format true
      include_tag_key true
      tag_key @log_name
      flush_interval 5s
    </match>
