apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: efk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: db-pvc
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
          - name: db-storage
            mountPath: /data/db
