resources:
  - namespace.yml
  - elasticsearch/statefulset.yml
  - elasticsearch/service.yml
  - kibana/deployment.yml
  - kibana/service.yml
  - fluentd/configmap.yml
  - fluentd/serviceaccount.yml
  - fluentd/clusterrole.yml
  - fluentd/clusterrolebinding.yml
  - fluentd/daemonset.yml
  - app/configmap.yml
  - app/deployment.yml
  - app/service.yml
  - db/pv.yml
  - db/pvc.yml
  - db/deployment.yml
  - db/service.yml
