apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: efk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      resources:
        requests:
          memory: "512Mi"
        limits:
          memory: "1Gi"
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.13.0
        env:
          - name: ELASTICSEARCH_HOSTS
            value: http://elasticsearch:9200
        ports:
        - containerPort: 5601
        readinessProbe:
          httpGet:
            path: /login
            port: 5601
          iinitialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /login
            port: 5601
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 6
