apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: efk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      resources:
        requests:
          memory: "512Mi"
        limits:
          memory: "1Gi"
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.13.0
        env:
          - name: ELASTICSEARCH_HOSTS
            value: http://elasticsearch:9200
          - name: ELASTICSEARCH_USERNAME
            valueFrom:
              secretKeyRef:
                name: elastic-credentials
                key: elastic-user
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: elastic-credentials
                key: elastic-password
        ports:
        - containerPort: 5601
